dependencies:
- alias: expose
  name: exposecontroller
  repository: https://jenkins-x-charts.github.io/v2
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: https://jenkins-x-charts.github.io/v2
  version: 2.3.118
- name: mqttserver
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.306
- name: prilux-vial-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.73
- name: priluxswiftlibrary
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.133
- name: priluxwebui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.884
